# Generated by Django 3.0 on 2022-08-24 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField(verbose_name='予約ID')),
                ('reservation_date', models.DateField(verbose_name='予約日付')),
                ('reservation_time', models.TimeField(verbose_name='予約時間')),
                ('book_staff', models.CharField(max_length=20, verbose_name='予約担当')),
                ('book_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('purpose', models.CharField(max_length=10, verbose_name='目的')),
                ('color', models.CharField(max_length=10, verbose_name='色')),
                ('modality', models.CharField(max_length=10, verbose_name='検査モダリティ')),
                ('part', models.CharField(max_length=10, verbose_name='検査部位')),
                ('memo', models.TextField(verbose_name='メモ')),
            ],
        ),
    ]
