# Generated by Django 3.0 on 2022-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_auto_20220824_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='modality',
            field=models.CharField(choices=[('1', 'MRI'), ('2', 'CT'), ('3', '超音波検査'), ('4', '基本検査'), ('5', '医師①'), ('6', '医師②(内視鏡)'), ('7', '医師③')], max_length=10, verbose_name='検査モダリティ'),
        ),
    ]
